### ISSUE TITLE
Ghost service name

### ISSUE THREAD

**Issue by bery** [mtpereira/ansible-ghost#6]
Hi, 

I am using your role to install and configure ghost and I would like to have multiple instances running on different port on one instance - would it be possible to make both the service name and init script configurable via vars? Or at least installed conditionally?

Thanks,

Lukas

**Comment by mtpereira** [comment]
Hello,

Well, templating the init and its path is the easy part. The bit that requires a bit more of thinking is the `ghosts_nginx_sites` variable defined on `vars/main.yml`. This defines the nginx sites created by the `jdauphant.nginx` role, included on the `dependencies` in the `meta/main.yml` file.

That role uses the keys on `nginx_sites` to define the location of the nginx sites configs (https://github.com/jdauphant/ansible-role-nginx/blob/master/tasks/configuration.yml#L13). As such, we'll need to set that dict dynamically or find another way around that particular issue.

As workaround, you can set `ghost_nginx_enabled` to false and take care of the nginx sites yourself.

I can't really tell when I'll get the time to do this, certainly not in the next couple of days, but PRs are more than welcome! :)

Thank you!

**Comment by bery** [comment]
Thanks for the quick reply! 

I already have disabled nginx configuration and used my own, still thanks for pointing that out. For the time being I will start working on rewriting the service name and come back to you once I will have something.

**Comment by mtpereira** [comment]
@bery Can you give a look at the PR #7 and check if it suites your needs, please?

**Comment by mtpereira** [comment]
I'll take the silence as a "yes" and merge it! 👍

**Comment by bery** [comment]
Sorry, for the late response. I will take a look as soon as I can and will let you know :)
